# Introduction

In this notebook, we will do a comprehensive analysis of the Android app market by comparing thousands of apps in the Google Play store.

# About the Dataset of Google Play Store Apps & Reviews

**Data Source:** <br>
App and review data was scraped from the Google Play Store by Lavanya Gupta in 2018. Original files listed [here](
https://www.kaggle.com/lava18/google-play-store-apps).

# Import Statements

In [20]:
import pandas as pd

import plotly.express as px

# Notebook Presentation

In [21]:
# Show numeric output in decimal format e.g., 2.15
pd.options.display.float_format = '{:,.2f}'.format

# Read the Dataset

In [22]:
df_apps = pd.read_csv('apps.csv')

# Data Cleaning

**Challenge**: How many rows and columns does `df_apps` have? What are the column names? Look at a random sample of 5 different rows with [.sample()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html).

In [23]:
df_apps.shape

(10841, 12)

In [24]:
df_apps.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size_MBs', 'Installs', 'Type',
       'Price', 'Content_Rating', 'Genres', 'Last_Updated', 'Android_Ver'],
      dtype='str')

In [25]:
df_apps.sample(10)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
2935,Jax Sheriff (FL),LIFESTYLE,4.20,53,16.00,"5,000",Free,0,Everyone,Lifestyle,"June 25, 2018",4.1 and up
5651,Next Launcher 3D Theme Stun-BW,PERSONALIZATION,4.40,2839,5.10,"100,000",Free,0,Everyone,Personalization,"January 11, 2014",2.2 and up
7594,M Launcher -Marshmallow 6.0,PERSONALIZATION,4.40,37234,7.30,"1,000,000",Free,0,Everyone,Personalization,"March 22, 2018",4.1 and up
803,Maricopa AH,MEDICAL,NaN,0,29.00,100,Free,0,Everyone,Medical,"July 16, 2018",4.0.3 and up
10187,AccuWeather: Daily Forecast & Live Weather Rep...,WEATHER,4.40,2053404,4.75,"50,000,000",Free,0,Everyone,Weather,"August 6, 2018",Varies with device
9718,Millionaire Quiz Free: Be Rich,FAMILY,3.80,66033,6.80,"10,000,000",Free,0,Everyone,Casual,"January 1, 2018",4.0 and up
3175,Advanced EX for HYUNDAI,TOOLS,2.70,168,0.17,"5,000",Paid,$4.99,Everyone,Tools,"March 14, 2015",1.6 and up
2959,AP Statistics Prep: Practice Tests and Flashcards,FAMILY,4.20,19,5.40,"5,000",Free,0,Everyone,Education,"July 3, 2018",4.1 and up
6451,Redfin Real Estate,HOUSE_AND_HOME,4.60,36857,19.00,"1,000,000",Free,0,Everyone,House & Home,"July 25, 2018",5.0 and up
4844,CV EXAMPLES,BUSINESS,4.10,423,20.00,"100,000",Free,0,Everyone,Business,"June 7, 2018",4.0.3 and up

### Drop Unused Columns

**Challenge**: Remove the columns called `Last_Updated` and `Android_Version` from the DataFrame. We will not use these columns.

In [26]:
# df_apps.drop(columns=["Last_Updated", "Android_Ver"], inplace=True)

df_apps

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
0,Ak Parti Yardım Toplama,SOCIAL,NaN,0,8.70,0,Paid,$13.99,Teen,Social,"July 28, 2017",4.1 and up
1,Ain Arabic Kids Alif Ba ta,FAMILY,NaN,0,33.00,0,Paid,$2.99,Everyone,Education,"April 15, 2016",3.0 and up
2,Popsicle Launcher for Android P 9.0 launcher,PERSONALIZATION,NaN,0,5.50,0,Paid,$1.49,Everyone,Personalization,"July 11, 2018",4.2 and up
3,Command & Conquer: Rivals,FAMILY,NaN,0,19.00,0,NaN,0,Everyone 10+,Strategy,"June 28, 2018",Varies with device
4,CX Network,BUSINESS,NaN,0,10.00,0,Free,0,Everyone,Business,"August 6, 2018",4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Subway Surfers,GAME,4.50,27723193,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade,"July 12, 2018",4.1 and up
10837,Subway Surfers,GAME,4.50,27724094,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade,"July 12, 2018",4.1 and up
10838,Subway Surfers,GAME,4.50,27725352,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade,"July 12, 2018",4.1 and up
10839,Subway Surfers,GAME,4.50,27725352,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade,"July 12, 2018",4.1 and up
10840,Subway Surfers,GAME,4.50,27711703,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade,"July 12, 2018",4.1 and up

### Find and Remove NaN values in Ratings

**Challenge**: How may rows have a NaN value (not-a-number) in the Ratings column? Create DataFrame called `df_apps_clean` that does not include these rows.

In [27]:
nan_rows = df_apps[df_apps['Rating'].isna()]

nan_rows.shape

(1474, 12)

In [28]:
df_apps_clean = df_apps.dropna()
df_apps_clean.shape

(9365, 12)

### Find and Remove Duplicates

**Challenge**: Are there any duplicates in data? Check for duplicates using the [.duplicated()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.duplicated.html) function. How many entries can you find for the "Instagram" app? Use [.drop_duplicates()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html) to remove any duplicates from `df_apps_clean`.

In [29]:
duplicates = df_apps[df_apps.duplicated()]

In [30]:
duplicates.shape

(483, 12)

In [31]:
df_apps_clean.drop_duplicates(inplace=True)

In [32]:
df_apps_clean.shape

(8891, 12)

In [33]:
df_apps_clean.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0,Everyone,Medical,"August 2, 2018",4.0.3 and up
28,Ra Ga Ba,GAME,5.00,2,20.00,1,Paid,$1.49,Everyone,Arcade,"February 8, 2017",2.3 and up
47,Mu.F.O.,GAME,5.00,2,16.00,1,Paid,$0.99,Everyone,Arcade,"March 3, 2017",2.3 and up
82,Brick Breaker BR,GAME,5.00,7,19.00,5,Free,0,Everyone,Arcade,"July 23, 2018",4.1 and up
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.00,1,4.60,5,Free,0,Everyone,Medical,"August 2, 2018",4.0 and up

# Find Highest Rated Apps

**Challenge**: Identify which apps are the highest rated. What problem might you encounter if you rely exclusively on ratings alone to determine the quality of an app?

In [34]:
df_apps_clean.sort_values('Rating', ascending=False).head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
151,EB Cash Collections,BUSINESS,5.00,1,4.30,5,Free,0,Everyone,Business,"July 31, 2018",4.4 and up
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.00,1,4.60,5,Free,0,Everyone,Medical,"August 2, 2018",4.0 and up
154,CZ-Help,BOOKS_AND_REFERENCE,5.00,2,1.40,5,Free,0,Everyone,Books & Reference,"July 13, 2018",4.4 and up
126,Tablet Reminder,MEDICAL,5.00,4,2.50,5,Free,0,Everyone,Medical,"August 3, 2018",4.1 and up
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0,Everyone,Medical,"August 2, 2018",4.0.3 and up

# Find 5 Largest Apps in terms of Size (MBs)

**Challenge**: What's the size in megabytes (MB) of the largest Android apps in the Google Play Store. Based on the data, do you think there could be limit in place or can developers make apps as large as they please?

In [35]:
df_apps_clean.sort_values('Size_MBs', ascending=False).head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
10689,Hungry Shark Evolution,GAME,4.50,6071542,100.00,"100,000,000",Free,0,Teen,Arcade,"July 25, 2018",4.1 and up
10687,Hungry Shark Evolution,GAME,4.50,6074334,100.00,"100,000,000",Free,0,Teen,Arcade,"July 25, 2018",4.1 and up
10688,Hungry Shark Evolution,GAME,4.50,6074627,100.00,"100,000,000",Free,0,Teen,Arcade,"July 25, 2018",4.1 and up
1795,Navi Radiography Pro,MEDICAL,4.70,11,100.00,500,Paid,$15.99,Everyone,Medical,"January 14, 2018",4.0.3 and up
8718,Mini Golf King - Multiplayer Game,GAME,4.50,531458,100.00,"5,000,000",Free,0,Everyone,Sports,"July 20, 2018",4.0.3 and up

# Find the 5 App with Most Reviews

**Challenge**: Which apps have the highest number of reviews? Are there any paid apps among the top 50?

In [36]:
df_apps_clean.sort_values('Reviews', ascending=False).head(50)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
10805,Facebook,SOCIAL,4.10,78158306,5.30,"1,000,000,000",Free,0,Teen,Social,"August 3, 2018",Varies with device
10811,Facebook,SOCIAL,4.10,78128208,5.30,"1,000,000,000",Free,0,Teen,Social,"August 3, 2018",Varies with device
10785,WhatsApp Messenger,COMMUNICATION,4.40,69119316,3.50,"1,000,000,000",Free,0,Everyone,Communication,"August 3, 2018",Varies with device
10797,WhatsApp Messenger,COMMUNICATION,4.40,69109672,3.50,"1,000,000,000",Free,0,Everyone,Communication,"August 3, 2018",Varies with device
10808,Instagram,SOCIAL,4.50,66577446,5.30,"1,000,000,000",Free,0,Teen,Social,"July 31, 2018",Varies with device
10806,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social,"July 31, 2018",Varies with device
10810,Instagram,SOCIAL,4.50,66509917,5.30,"1,000,000,000",Free,0,Teen,Social,"July 31, 2018",Varies with device
10790,Messenger – Text and Video Chat for Free,COMMUNICATION,4.00,56646578,3.50,"1,000,000,000",Free,0,Everyone,Communication,"August 1, 2018",Varies with device
10784,Messenger – Text and Video Chat for Free,COMMUNICATION,4.00,56642847,3.50,"1,000,000,000",Free,0,Everyone,Communication,"August 1, 2018",Varies with device
10652,Clash of Clans,GAME,4.60,44893888,98.00,"100,000,000",Free,0,Everyone 10+,Strategy,"July 15, 2018",4.1 and up
10650,Clash of Clans,GAME,4.60,44891723,98.00,"100,000,000",Free,0,Everyone 10+,Strategy,"July 15, 2018",4.1 and up
10653,Clash of Clans,FAMILY,4.60,44881447,98.00,"100,000,000",Free,0,Everyone 10+,Strategy,"July 15, 2018",4.1 and up
10744,Clean Master- Space Cleaner & Antivirus,TOOLS,4.70,42916526,3.40,"500,000,000",Free,0,Everyone,Tools,"August 3, 2018",Varies with device
10838,Subway Surfers,GAME,4.50,27725352,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade,"July 12, 2018",4.1 and up
10837,Subway Surfers,GAME,4.50,27724094,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade,"July 12, 2018",4.1 and up
10836,Subway Surfers,GAME,4.50,27723193,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade,"July 12, 2018",4.1 and up
10835,Subway Surfers,GAME,4.50,27722264,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade,"July 12, 2018",4.1 and up
10840,Subway Surfers,GAME,4.50,27711703,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade,"July 12, 2018",4.1 and up
10828,YouTube,VIDEO_PLAYERS,4.30,25655305,4.65,"1,000,000,000",Free,0,Teen,Video Players & Editors,"August 2, 2018",Varies with device
10830,YouTube,VIDEO_PLAYERS,4.30,25623548,4.65,"1,000,000,000",Free,0,Teen,Video Players & Editors,"August 2, 2018",Varies with device
10746,"Security Master - Antivirus, VPN, AppLock, Boo...",TOOLS,4.70,24900999,3.40,"500,000,000",Free,0,Everyone,Tools,"August 4, 2018",Varies with device
10588,Clash Royale,GAME,4.60,23136735,97.00,"100,000,000",Free,0,Everyone 10+,Strategy,"June 27, 2018",4.1 and up
10586,Clash Royale,GAME,4.60,23134775,97.00,"100,000,000",Free,0,Everyone 10+,Strategy,"June 27, 2018",4.1 and up
10584,Clash Royale,GAME,4.60,23133508,97.00,"100,000,000",Free,0,Everyone 10+,Strategy,"June 27, 2018",4.1 and up
10592,Clash Royale,FAMILY,4.60,23125280,97.00,"100,000,000",Free,0,Everyone 10+,Strategy,"June 27, 2018",4.1 and up
10767,Candy Crush Saga,GAME,4.40,22430188,74.00,"500,000,000",Free,0,Everyone,Casual,"July 5, 2018",4.1 and up
10766,Candy Crush Saga,GAME,4.40,22429716,74.00,"500,000,000",Free,0,Everyone,Casual,"July 5, 2018",4.1 and up
10764,Candy Crush Saga,GAME,4.40,22428456,74.00,"500,000,000",Free,0,Everyone,Casual,"July 5, 2018",4.1 and up
10763,Candy Crush Saga,GAME,4.40,22426677,74.00,"500,000,000",Free,0,Everyone,Casual,"July 5, 2018",4.1 and up
10769,Candy Crush Saga,FAMILY,4.40,22419455,74.00,"500,000,000",Free,0,Everyone,Casual,"July 5, 2018",4.1 and up
10771,UC Browser - Fast Download Private & Secure,COMMUNICATION,4.50,17714850,40.00,"500,000,000",Free,0,Teen,Communication,"August 2, 2018",4.0 and up
10770,UC Browser - Fast Download Private & Secure,COMMUNICATION,4.50,17712922,40.00,"500,000,000",Free,0,Teen,Communication,"August 2, 2018",4.0 and up
10737,Snapchat,SOCIAL,4.00,17015352,5.30,"500,000,000",Free,0,Teen,Social,"July 30, 2018",Varies with device
10735,Snapchat,SOCIAL,4.00,17014787,5.30,"500,000,000",Free,0,Teen,Social,"July 30, 2018",Varies with device
10736,Snapchat,SOCIAL,4.00,17014705,5.30,"500,000,000",Free,0,Teen,Social,"July 30, 2018",Varies with device
10738,Snapchat,SOCIAL,4.00,17000166,5.30,"500,000,000",Free,0,Teen,Social,"July 30, 2018",Varies with device
10489,"360 Security - Free Antivirus, Booster, Cleaner",TOOLS,4.60,16771865,3.40,"100,000,000",Free,0,Everyone,Tools,"August 4, 2018",Varies with device
10732,My Talking Tom,GAME,4.50,14892469,36.00,"500,000,000",Free,0,Everyone,Casual,"July 19, 2018",4.1 and up
10731,My Talking Tom,GAME,4.50,14891223,36.00,"500,000,000",Free,0,Everyone,Casual,"July 19, 2018",4.1 and up
10733,My Talking Tom,FAMILY,4.50,14885236,19.00,"500,000,000",Free,0,Everyone,Casual,"July 19, 2018",4.1 and up
10599,8 Ball Pool,GAME,4.50,14201891,52.00,"100,000,000",Free,0,Everyone,Sports,"July 31, 2018",4.0.3 and up
10600,8 Ball Pool,GAME,4.50,14201604,52.00,"100,000,000",Free,0,Everyone,Sports,"July 31, 2018",4.0.3 and up
10598,8 Ball Pool,GAME,4.50,14200550,52.00,"100,000,000",Free,0,Everyone,Sports,"July 31, 2018",4.0.3 and up
10596,8 Ball Pool,GAME,4.50,14200344,52.00,"100,000,000",Free,0,Everyone,Sports,"July 31, 2018",4.0.3 and up
10595,8 Ball Pool,GAME,4.50,14198602,52.00,"100,000,000",Free,0,Everyone,Sports,"July 31, 2018",4.0.3 and up
10594,8 Ball Pool,GAME,4.50,14198297,52.00,"100,000,000",Free,0,Everyone,Sports,"July 31, 2018",4.0.3 and up
10602,8 Ball Pool,SPORTS,4.50,14184910,52.00,"100,000,000",Free,0,Everyone,Sports,"July 31, 2018",4.0.3 and up
10302,DU Battery Saver - Battery Charger & Battery Life,TOOLS,4.50,13479633,14.00,"100,000,000",Free,0,Everyone,Tools,"June 5, 2018",4.0 and up
10371,BBM - Free Calls & Messages,COMMUNICATION,4.30,12843436,3.50,"100,000,000",Free,0,Everyone,Communication,"August 2, 2018",4.0.3 and up
10354,BBM - Free Calls & Messages,COMMUNICATION,4.30,12842860,3.50,"100,000,000",Free,0,Everyone,Communication,"August 2, 2018",4.0.3 and up

# Plotly Pie and Donut Charts - Visualise Categorical Data: Content Ratings

In [37]:
ratings = df_apps_clean.Content_Rating.value_counts()
ratings

Content_Rating
Everyone           7094
Teen               1022
Mature 17+          411
Everyone 10+        360
Adults only 18+       3
Unrated               1
Name: count, dtype: int64

In [38]:
fig = px.pie(labels=ratings.index, values=ratings.values)

fig.show()

In [39]:
fig = px.pie(labels=ratings.index,
values=ratings.values,
title="Content Rating",
names=ratings.index,
)
fig.update_traces(textposition='outside', textinfo='percent+label')
 
fig.show()

In [40]:
fig = px.pie(labels=ratings.index,
values=ratings.values,
title="Content Rating",
names=ratings.index,
hole=0.6,
)
fig.update_traces(textposition='inside', textfont_size=15, textinfo='percent')
 
fig.show()

# Numeric Type Conversion: Examine the Number of Installs

**Challenge**: How many apps had over 1 billion (that's right - BILLION) installations? How many apps just had a single install? 

Check the datatype of the Installs column.

Count the number of apps at each level of installations. 

Convert the number of installations (the Installs column) to a numeric data type. Hint: this is a 2-step process. You'll have make sure you remove non-numeric characters first.

# Find the Most Expensive Apps, Filter out the Junk, and Calculate a (ballpark) Sales Revenue Estimate

Let's examine the Price column more closely.

**Challenge**: Convert the price column to numeric data. Then investigate the top 20 most expensive apps in the dataset.

Remove all apps that cost more than $250 from the `df_apps_clean` DataFrame.

Add a column called 'Revenue_Estimate' to the DataFrame. This column should hold the price of the app times the number of installs. What are the top 10 highest grossing paid apps according to this estimate? Out of the top 10 highest grossing paid apps, how many are games?

### The most expensive apps sub $250

### Highest Grossing Paid Apps (ballpark estimate)

# Plotly Bar Charts & Scatter Plots: Analysing App Categories

### Vertical Bar Chart - Highest Competition (Number of Apps)

### Horizontal Bar Chart - Most Popular Categories (Highest Downloads)

### Category Concentration - Downloads vs. Competition

**Challenge**: 
* First, create a DataFrame that has the number of apps in one column and the number of installs in another:

<img src=https://imgur.com/uQRSlXi.png width="350">

* Then use the [plotly express examples from the documentation](https://plotly.com/python/line-and-scatter/) alongside the [.scatter() API reference](https://plotly.com/python-api-reference/generated/plotly.express.scatter.html)to create scatter plot that looks like this. 

<img src=https://imgur.com/cHsqh6a.png>

*Hint*: Use the size, hover_name and color parameters in .scatter(). To scale the yaxis, call .update_layout() and specify that the yaxis should be on a log-scale like so: yaxis=dict(type='log')

# Extracting Nested Data from a Column

**Challenge**: How many different types of genres are there? Can an app belong to more than one genre? Check what happens when you use .value_counts() on a column with nested values? See if you can work around this problem by using the .split() function and the DataFrame's [.stack() method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.stack.html).

# Colour Scales in Plotly Charts - Competition in Genres

**Challenge**: Can you create this chart with the Series containing the genre data? 

<img src=https://imgur.com/DbcoQli.png width=400>

Try experimenting with the built in colour scales in Plotly. You can find a full list [here](https://plotly.com/python/builtin-colorscales/). 

* Find a way to set the colour scale using the color_continuous_scale parameter. 
* Find a way to make the color axis disappear by using coloraxis_showscale.

# Grouped Bar Charts: Free vs. Paid Apps per Category

**Challenge**: Use the plotly express bar [chart examples](https://plotly.com/python/bar-charts/#bar-chart-with-sorted-or-ordered-categories) and the [.bar() API reference](https://plotly.com/python-api-reference/generated/plotly.express.bar.html#plotly.express.bar) to create this bar chart: 

<img src=https://imgur.com/LE0XCxA.png>

You'll want to use the `df_free_vs_paid` DataFrame that you created above that has the total number of free and paid apps per category. 

See if you can figure out how to get the look above by changing the `categoryorder` to 'total descending' as outlined in the documentation here [here](https://plotly.com/python/categorical-axes/#automatically-sorting-categories-by-name-or-total-value).

# Plotly Box Plots: Lost Downloads for Paid Apps

**Challenge**: Create a box plot that shows the number of Installs for free versus paid apps. How does the median number of installations compare? Is the difference large or small?

Use the [Box Plots Guide](https://plotly.com/python/box-plots/) and the [.box API reference](https://plotly.com/python-api-reference/generated/plotly.express.box.html) to create the following chart. 

<img src=https://imgur.com/uVsECT3.png>

# Plotly Box Plots: Revenue by App Category

**Challenge**: See if you can generate the chart below: 

<img src=https://imgur.com/v4CiNqX.png>

Looking at the hover text, how much does the median app earn in the Tools category? If developing an Android app costs $30,000 or thereabouts, does the average photography app recoup its development costs?

Hint: I've used 'min ascending' to sort the categories.

# How Much Can You Charge? Examine Paid App Pricing Strategies by Category

**Challenge**: What is the median price price for a paid app? Then compare pricing by category by creating another box plot. But this time examine the prices (instead of the revenue estimates) of the paid apps. I recommend using `{categoryorder':'max descending'}` to sort the categories.